name: Prettier

on: [push]

jobs:
  build:
      name: Prettier
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - uses: npm -g -install

      - run: npm run prettier --write --config .prettierrc.json '*.js'
      - run: git status



